---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: test/fixtures/config/.eslintrc
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**.js"
exclude_paths:
- test/
- docs/
- index.js
- index.d.ts
- gulpfile.js
